import type { Card } from '../types/domain';

export const CARDS: Card[] = [
  {
    id: 'desmayo',
    title: 'Protocolo de Desmayo',
    category: 'Emergencia médica',
    severity: 'critical',
    blurb: 'Pérdida súbita de conciencia. Verifica respiración, asegura la vía aérea y eleva las piernas.',
    icon: 'HeartPulse',
    tint: 'red',
    eta: '2 min',
    steps: [
      'Coloca a la persona boca arriba sobre superficie firme.',
      'Eleva las piernas 30 cm para retornar flujo cerebral.',
      'Afloja ropa que comprima cuello, pecho o cintura.',
      'Verifica respiración cada 15 segundos.',
      'Si no responde en 60s, llama a Emergencias.',
    ],
    long: 'El desmayo (síncope) es una pérdida breve de conciencia por reducción del flujo sanguíneo cerebral. La mayoría de los casos son benignos y autolimitados, pero requieren observación inmediata para descartar causas cardíacas o neurológicas. No abandonar al paciente. Mantener la zona ventilada.',
    triage: [
      { q: '¿La persona respira con normalidad?', opts: ['Sí', 'No', 'No estoy seguro'] },
      { q: '¿Responde al hablarle o tocarle el hombro?', opts: ['Sí, responde', 'No responde'] },
      { q: '¿Hay sospecha de lesión en cabeza o cuello?', opts: ['No', 'Sí'] },
    ],
    verdict: {
      level: 'ALERTA ROJA',
      title: 'Llamar a Emergencias ahora',
      body: 'Indicios de paro respiratorio o pérdida prolongada de conciencia.',
    },
  },
  {
    id: 'llanta',
    title: 'Cambio de Llanta',
    category: 'Asistencia vehicular',
    severity: 'normal',
    blurb: 'Reemplazo seguro de neumático en orilla del camino. Estaciona en plano y activa intermitentes.',
    icon: 'CircleDot',
    tint: 'zinc',
    eta: '18 min',
    steps: [
      'Estaciona en superficie plana y activa intermitentes.',
      'Asegura el vehículo con freno de mano y cuñas.',
      'Afloja birlos un cuarto de vuelta antes de levantar.',
      'Eleva con el gato hasta despegar la llanta.',
      'Retira birlos, sustituye llanta, ajusta en cruz.',
    ],
    long: 'El cambio de neumático en ruta debe realizarse fuera del flujo vehicular, a más de 10 metros del acotamiento si es posible. Verifica la presión de la llanta de refacción antes de iniciar. No olvides reapretar los birlos después de recorrer 50 km.',
    triage: [
      { q: '¿Estás en una superficie plana y segura?', opts: ['Sí', 'No', 'Parcialmente'] },
      { q: '¿Tienes gato hidráulico y llave de cruz?', opts: ['Sí', 'No'] },
      { q: '¿La llanta de refacción tiene aire?', opts: ['Sí', 'No lo sé'] },
    ],
    verdict: {
      level: 'PROCEDE',
      title: 'Continúa con el procedimiento',
      body: 'Condiciones verificadas. Sigue los pasos del protocolo.',
    },
  },
  {
    id: 'fractura',
    title: 'Fractura de Brazo',
    category: 'Primeros auxilios',
    severity: 'normal',
    blurb: 'Inmoviliza la extremidad sin recolocar el hueso. Aplica frío indirecto sobre la zona.',
    icon: 'Bone',
    tint: 'amber',
    eta: '6 min',
    steps: [
      'No intentes recolocar el hueso.',
      'Inmoviliza con férula improvisada (cartón, revista).',
      'Aplica frío envuelto en tela, máximo 15 min.',
      'Eleva ligeramente para reducir inflamación.',
      'Traslada al servicio médico más cercano.',
    ],
    long: 'Una fractura puede ser cerrada (sin herida visible) o expuesta (con hueso atravesando piel). En ambos casos, lo prioritario es inmovilizar la zona y evitar movimientos que agraven la lesión.',
    triage: [
      { q: '¿Hay hueso expuesto o sangrado abundante?', opts: ['No', 'Sí'] },
      { q: '¿La persona puede mover los dedos?', opts: ['Sí', 'Con dolor', 'No'] },
    ],
    verdict: {
      level: 'TRASLADO',
      title: 'Traslada a urgencias',
      body: 'Requiere evaluación radiológica en las próximas 2 horas.',
    },
  },
  {
    id: 'quemadura',
    title: 'Quemadura de 2° Grado',
    category: 'Primeros auxilios',
    severity: 'normal',
    blurb: 'Enfría con agua corriente 10–20 minutos. No revientes ampollas.',
    icon: 'Flame',
    tint: 'amber',
    eta: '4 min',
    steps: [
      'Retira a la persona de la fuente de calor.',
      'Enjuaga con agua corriente fría 10–20 min.',
      'No apliques pomadas, hielo ni remedios caseros.',
      'Cubre con apósito estéril o tela limpia.',
      'Acude a evaluación médica.',
    ],
    long: 'Las quemaduras de segundo grado afectan epidermis y dermis, generan ampollas y dolor intenso. La hidratación local con agua corriente reduce profundidad y riesgo de infección.',
    triage: [
      { q: '¿La quemadura cubre más del 10% del cuerpo?', opts: ['Sí', 'No'] },
      { q: '¿Afecta cara, manos o genitales?', opts: ['Sí', 'No'] },
    ],
    verdict: {
      level: 'EVALUACIÓN',
      title: 'Acude al servicio médico',
      body: 'Quemadura con riesgo de infección. Mantén apósito limpio.',
    },
  },
  {
    id: 'corte',
    title: 'Corte Profundo',
    category: 'Primeros auxilios',
    severity: 'normal',
    blurb: 'Presión directa con apósito limpio. Eleva la extremidad sobre el nivel del corazón.',
    icon: 'Scissors',
    tint: 'zinc',
    eta: '3 min',
    steps: [
      'Lava las manos antes de tocar la herida.',
      'Aplica presión directa con tela limpia.',
      'Eleva la extremidad sobre el corazón.',
      'No retires el apósito si se empapa: añade encima.',
      'Acude a sutura en menos de 6 horas.',
    ],
    long: 'Las heridas profundas que exponen tejido subcutáneo requieren sutura o adhesivos quirúrgicos en menos de 6 horas para reducir riesgo de cicatriz e infección.',
    triage: [
      { q: '¿El sangrado se detiene con presión?', opts: ['Sí', 'No'] },
      { q: '¿Se ve hueso, tendón o grasa?', opts: ['No', 'Sí'] },
    ],
    verdict: {
      level: 'TRASLADO',
      title: 'Requiere sutura',
      body: 'Acude al servicio de urgencias en menos de 6 horas.',
    },
  },
];

export const HISTORY_DEFAULT = ['desmayo', 'llanta', 'fractura', 'quemadura', 'corte'];
